- hosts: workstations
  gather_facts: yes
  become: yes

  tasks:
    - name: Install DockerCE
      package:
        name: docker-ce
        state: present



- hosts: artifactory
  gather_facts: yes
  become: yes

  tasks:
    - name: Upload app distr to artfactory
      uri:
        url: "https://{{ project-registry }}/dbo-1.0-SNAPSHOT.jar"
        src: ../backend/dbo-1.0-SNAPSHOT.jar
        method: PUT
        return_content: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        force_basic_auth: true
        status_code: 201
        headers:
          Content-Type: application/octet-stream
          Accept: application/json

    - name: Upload app source to artfactory
      uri:
        url: "https://{{ project-registry }}/dbo-1.0-SNAPSHOT-src.zip"
        src: ../backend/dbo-1.0-SNAPSHOT-src.zip
        method: PUT
        return_content: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        force_basic_auth: true
        status_code: 201
        headers:
          Content-Type: application/octet-stream
          Accept: application/json
